```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r}
library(targets)
library(dplyr)
library(EpiSewer)
library(ggplot2)
source("code/pipeline/utils_pipeline.R")
source("code/pipeline/utils_real_time.R")
source("data/assumptions/epi_params_EpiSewer-study.R")
source("code/local_config.R")
```

Create pipeline folders if they do not exist
```{r}
setup_pipeline("_load_per_case")
setup_pipeline("_load_variation")
```

## Run pipelines

```{r, include = FALSE}
run_pipeline(targets_proj_name = "_load_per_case", submit = T)
if(length(tar_read(jobs_EpiSewer_invalid))>0) {
  warning("There are invalid jobs.")
}
```

```{r, include = FALSE}
run_pipeline(targets_proj_name = "_load_variation", submit = T)
if(length(tar_read(jobs_EpiSewer_invalid))>0) {
  warning("There are invalid jobs.")
}
```

Check results
```{r}
all_pipelines <- c("_load_per_case", "_load_variation")
rbindlist(lapply(all_pipelines, function(pipeline) {
  suppressMessages(setup_pipeline(pipeline))
  return(tar_read(job_EpiSewer_submission) |>
    mutate(total = 1, .before = exists) |>
    summarise(across(total:submitted, sum, na.rm = T)) |> 
    mutate(pipeline = pipeline, .before = total)
    )
}))
```

## Load results
```{r}
all_pipelines <- c("_load_per_case", "_load_variation")
job_EpiSewer_result <- load_EpiSewer_results(all_pipelines)
data_PCR_agg_select <- get_data_PCR_agg_select(all_pipelines)
data_flow_select <- get_data_flow_select(all_pipelines)
```

```{r}
zeta_prior_to_name <- function(prior) {
  if (length(prior) == 0) {
    "0%"
  } else if (all(prior == c(2,0))) {
    "200%"
  } else if (all(prior == c(1,0))) {
    "100%"
  }
}

results_index <- bind_rows(lapply(job_EpiSewer_result, function(x) data.frame(
  wwtp = x$job$selection$wwtp,
  target = x$job$selection$target,
  estimation_date = lubridate::as_date(x$job$selection$date_select[[1]]["to"]),
  load_per_case_mult = x$job$selection$sensitivity_load_per_case[[1]]$multiplier,
  load_variation = zeta_prior_to_name(x$job$data$nu_zeta_prior)
  )))
rownames(results_index) <- NULL
results_index$i <- 1:nrow(results_index)

get_result_label <- function(x) {
  paste(
    x$summary$R[type == "estimate", max(date)],
    x$job$selection$wwtp,
    x$job$selection$target,
    paste("Multiplier:", x$job$selection$sensitivity_load_per_case[[1]]$multiplier),
    paste("Load variation:", zeta_prior_to_name(x$job$data$nu_zeta_prior)),
    sep = " | "
    )
}
```

## Plotting

### Load per case
```{r}
wwtp_select = "ARA Werdhoelzli"
target_select = "SARS-N2"
estimation_date_select = "2024-07-31"
results_select <- results_index |> filter(wwtp == wwtp_select, target == target_select, estimation_date == estimation_date_select) |> filter(load_variation == "100%") |> group_by(load_per_case_mult) |> slice_head()

baseline_select <- results_index |> filter(wwtp == wwtp_select, target == target_select, estimation_date == estimation_date_select) |> filter(load_variation == "100%") |> filter(load_per_case_mult == 1) |> group_by(load_per_case_mult) |> slice_head()
```

```{r fig.width = 10, fig.height = 7}
baseline_load <- job_EpiSewer_result[[baseline_select$i]]$job$metainfo$load_per_case

plot_res <- job_EpiSewer_result[results_select$i]
names(plot_res) <- baseline_load * results_select$load_per_case_mult
names(plot_res) <- format(as.numeric(names(plot_res)), scientific = TRUE)
names(plot_res) <- format(as.numeric(names(plot_res)), digits = 2)
names(plot_res) <- paste0(names(plot_res), " [gene copies / infection]")

inf_plot <- plot_infections(plot_res, forecast = FALSE) + 
  coord_cartesian(ylim = c(0,NA)) + 
  facet_wrap(~model, scales = "free_y", ncol = 1) + 
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "white")
    )

R_plot <- plot_R(c(plot_res, list(baseline = job_EpiSewer_result[[baseline_select$i]])), forecast = FALSE, base_model = "baseline") + 
  coord_cartesian(ylim = c(0.75,1.3)) + 
  facet_wrap(~model, scales = "free_y", ncol = 1) + 
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "white")
    )

cowplot::plot_grid(inf_plot, R_plot, nrow = 1, align = "h")
ggsave(here::here("figures", "load_per_case", "sensitivity_mean_load.pdf"), width = 10, height = 7)
```


### Load variation
```{r}
wwtp_select = "ARA Werdhoelzli"
target_select = "RSV-N"
estimation_date_select = "2024-07-31"
results_select <- results_index |> filter(wwtp == wwtp_select, target == target_select, estimation_date == estimation_date_select) |> filter(load_per_case_mult == 1) |> group_by(load_variation) |> slice_head()

baseline_select <- results_index |> filter(wwtp == wwtp_select, target == target_select, estimation_date == estimation_date_select) |> filter(load_per_case_mult == 1) |> filter(load_variation == "100%") |> group_by(load_variation) |> slice_head()
```

```{r fig.width = 10, fig.height = 5}
plot_res <- job_EpiSewer_result[results_select$i]
names(plot_res) <- paste0("", results_select$load_variation)
load_plot <- plot_load(plot_res, forecast = FALSE) + 
  coord_cartesian(ylim = c(0,NA)) + 
  facet_wrap(~model, scales = "free_y", ncol = 1) + 
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "white")
    )

R_plot <- plot_R(c(plot_res, list(baseline = job_EpiSewer_result[[baseline_select$i]])), forecast = FALSE, base_model = "baseline") + 
  coord_cartesian(ylim = c(0.45,1.8)) + 
  facet_wrap(~model, scales = "free_y", ncol = 1) + 
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "white")
    )

cowplot::plot_grid(load_plot, R_plot, nrow = 1, align = "h")
ggsave(here::here("figures", "load_per_case", "sensitivity_individual_load_variation.pdf"), width = 10, height = 5)
```

## Pruning
The following code can be used to clean the pipeline from unused objects

```{r}
tar_prune()
```
