```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r}
library(targets)
library(dplyr)
library(EpiSewer)
library(ggplot2)
source("code/pipeline/utils_pipeline.R")
source("code/pipeline/utils_real_time.R")
source("data/assumptions/epi_params_EpiSewer-study.R")
source("code/local_config.R")
```

## Run pipelines

Create pipeline folders if it does not exist
```{r}
setup_pipeline("_load_calibration_underreporting")
```

```{r, include = FALSE}
all_pipelines <- c("_load_calibration_underreporting")
for (selection_to_run in all_pipelines) {
  run_pipeline(targets_proj_name = selection_to_run, submit = TRUE)
  if(length(tar_read(jobs_EpiSewer_invalid))>0) {
    warning("There are invalid jobs.")
  }
}
```

Check results
```{r}
rbindlist(lapply(all_pipelines, function(pipeline) {
  suppressMessages(setup_pipeline(pipeline))
  return(tar_read(job_EpiSewer_submission) |>
    mutate(total = 1, .before = exists) |>
    summarise(across(total:submitted, sum, na.rm = T)) |> 
    mutate(pipeline = pipeline, .before = total)
    )
}))
```

## Load results
```{r}
job_EpiSewer_result_underrep <- load_EpiSewer_results("_load_calibration_underreporting")
data_PCR_agg_select_underrep <- get_data_PCR_agg_select("_load_calibration_underreporting")
data_flow_select_underrep <- get_data_flow_select("_load_calibration_underreporting")

# Here we use the models fitted for the main analysis as a comparison
job_EpiSewer_result <- load_EpiSewer_results("_overview_23-24")
data_PCR_agg_select <- get_data_PCR_agg_select("_overview_23-24")
data_flow_select <- get_data_flow_select("_overview_23-24")
```

Build index
```{r}
results_index_underrep <- bind_rows(lapply(job_EpiSewer_result_underrep, function(x) {
  if (length(x) == 0) { data.frame(wwtp = NA, target = NA, estimation_date = NA)
  } else {
    return(data.frame(
      wwtp = x$job$selection$wwtp,
      target = x$job$selection$target,
      estimation_date = lubridate::as_date(x$job$selection$date_select[[1]]["to"]),
      season = ifelse(lubridate::as_date(x$job$selection$date_select[[1]]["to"])<"2023-08-01","2022/23","2023/24"),
      mobility = TRUE
  ))}
  }))
rownames(results_index_underrep) <- NULL
results_index_underrep$i <- 1:nrow(results_index_underrep)

results_index <- bind_rows(lapply(job_EpiSewer_result, function(x) {
  if (length(x) == 0) { data.frame(wwtp = NA, target = NA, estimation_date = NA)
  } else {
    return(data.frame(
      wwtp = x$job$selection$wwtp,
      target = x$job$selection$target,
      estimation_date = lubridate::as_date(x$job$selection$date_select[[1]]["to"]),
      season = ifelse(lubridate::as_date(x$job$selection$date_select[[1]]["to"])<"2023-08-01","2022/23","2023/24"),
      mobility = FALSE
  ))}
  }))
rownames(results_index) <- NULL
results_index$i <- 1:nrow(results_index)
```

## Plotting
```{r}
palette_reporting <- c("Underreporting"="#0072B5FF", "Baseline"="black")
```

```{r fig.height = 12, fig.width = 10}
selection <- list(wwtp_select = "ARA Werdhoelzli", target_select = "IAV-M", R_lim = c(0.7, 1.4))
date_lim <- as.Date(c("2023-10-30", "2024-04-15"))

results_select <- list(
    Underreporting = job_EpiSewer_result_underrep[[results_index_underrep |> filter(wwtp == selection$wwtp_select, target == selection$target_select) |> pull(i) |> as.integer()]],
  Baseline = job_EpiSewer_result[[results_index |> filter(wwtp == selection$wwtp_select, target == selection$target_select) |> pull(i) |> as.integer()]]
)

ymax <- results_select[[1]]$summary$concentration[, max(upper_0.95)]
                                        
concentration_plot <- plot_concentration(
  results_select,
  concentration_col = "gc_per_mlww",
  forecast = FALSE, median = T) + theme(legend.position = "top", legend.title = element_text()) + 
  coord_cartesian(ylim = c(0, ymax)) +
  scale_color_manual(name = "Reporting scenario", values = palette_reporting) +
  scale_fill_manual(name = "Reporting scenario", values = palette_reporting) +
  coord_cartesian(xlim = date_lim) +
  ylab(expression(C[t]~plain("[gc / mL]"))) +
  geom_vline(xintercept = as.Date("2023-12-24"), linetype = "dashed", color = "grey")

load_plot <- plot_load(results_select, median = T, forecast = FALSE) + 
  theme(legend.position = "top", legend.title = element_text()) +
  scale_color_manual(name = "Reporting scenario", values = palette_reporting) +
  scale_fill_manual(name = "Reporting scenario", values = palette_reporting) +
  coord_cartesian(xlim = date_lim) +
  geom_vline(xintercept = as.Date("2023-12-24"), linetype = "dashed", color = "grey")

infection_plot <- plot_infections(results_select, median = T, forecast = FALSE) + 
  theme(legend.position = "top", legend.title = element_text()) +
  scale_color_manual(name = "Reporting scenario", values = palette_reporting) +
  scale_fill_manual(name = "Reporting scenario", values = palette_reporting) +
  coord_cartesian(xlim = date_lim) +
  geom_vline(xintercept = as.Date("2023-12-24"), linetype = "dashed", color = "grey")

R_plot <- plot_R(results_select, median = T, forecast = FALSE) + 
  theme(legend.position = "top", legend.title = element_text()) +
  scale_color_manual(name = "Reporting scenario", values = palette_reporting) +
  scale_fill_manual(name = "Reporting scenario", values = palette_reporting) +
  coord_cartesian(xlim = date_lim, ylim = selection$R_lim) +
  geom_vline(xintercept = as.Date("2023-12-24"), linetype = "dashed", color = "grey")

# extract legend from R plot
legend <- cowplot::get_legend(R_plot + theme(legend.position = "top"))

combined_plot <- cowplot::plot_grid(legend, cowplot::plot_grid(
  plot_underrep_proportion + theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank()),
  plot_underrep_incidence + theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank()),
  plot_underrep_load_per_case + theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank()),
  infection_plot + theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank()),
  R_plot + theme(legend.position = "none", axis.title.x = element_blank()) + ylab(expression(R[t])),
  ncol = 1, align = "v", rel_heights = c(0.7,0.8,0.7,1,1), labels = "AUTO"
), ncol = 1, rel_heights = c(0.03, 0.95))

print(combined_plot)
ggsave(plot = combined_plot, file = here::here("figures", "load_calibration_underreporting", paste0("load_calibration_underreporting_", selection$wwtp_select, "_", selection$target_select, ".pdf")), width = 10, height = 12)
ggsave(plot = combined_plot, file = here::here("figures", "load_calibration_underreporting", paste0("load_calibration_underreporting_", selection$wwtp_select, "_", selection$target_select, ".png")), width = 10, height = 12)
```

