```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r}
library(targets)
library(dplyr)
library(EpiSewer)
library(ggplot2)
source("code/pipeline/utils_pipeline.R")
source("code/pipeline/utils_real_time.R")
source("data/assumptions/epi_params_EpiSewer-study.R")
source("code/local_config.R")
```

## Simulate mobility data
```{r}
data_mobility <- read_csv(here::here("data", "ww_data", "dPCR_time_series_until_2025-05-31.csv")) |> 
  filter(wastewater_treatment_plant.name == "ARA Werdhoelzli", target == "SARS-N2", collection_date >= "2023-08-01", collection_date <= "2024-07-31")

# identify weekends and holidays
holidays <- as.Date(c("2023-08-01", "2023-12-25", "2023-12-26", "2024-01-01", "2024-03-29", "2024-04-01", "2024-05-01", "2024-05-09", "2024-05-20"))

data_mobility <- data_mobility |> 
  mutate(
    weekend_holiday = lubridate::wday(collection_date, label = TRUE) %in% c("Sat", "Sun") | collection_date %in% holidays,
    mobility_factor = ifelse(weekend_holiday, 0.75, 1), # assuming that mobility (and thus sewage load) is 25% lower on weekends/holidays
    gc_per_lww = gc_per_lww * mobility_factor
    )

data_mobility |> 
  ggplot(aes(x = collection_date, y = gc_per_lww * flow)) +
  geom_line() +
  geom_point(data = data_mobility |> filter(weekend_holiday), color = "red", size = 0.5) +
  theme_bw() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b\n%Y") +
  ylab(expression(Load[t]~plain("[gc / day]")))

write_csv(data_mobility, here::here("data", "ww_data", "dPCR_time_series_simulated_mobility.csv"))
```

## Run pipelines

Create pipeline folders if it does not exist
```{r}
setup_pipeline("_mobility_commuting")
```

```{r, include = FALSE}
all_pipelines <- c("_mobility_commuting")
for (selection_to_run in all_pipelines) {
  run_pipeline(targets_proj_name = selection_to_run, submit = TRUE)
  if(length(tar_read(jobs_EpiSewer_invalid))>0) {
    warning("There are invalid jobs.")
  }
}
```

Check results
```{r}
rbindlist(lapply(all_pipelines, function(pipeline) {
  suppressMessages(setup_pipeline(pipeline))
  return(tar_read(job_EpiSewer_submission) |>
    mutate(total = 1, .before = exists) |>
    summarise(across(total:submitted, sum, na.rm = T)) |> 
    mutate(pipeline = pipeline, .before = total)
    )
}))
```

## Load results
```{r}
job_EpiSewer_result_mobility <- load_EpiSewer_results("_mobility_commuting")
data_PCR_agg_select_mobility <- get_data_PCR_agg_select("_mobility_commuting")
data_flow_select_mobility <- get_data_flow_select("_mobility_commuting")

# Here we use the models fitted for the main analysis as a comparison
job_EpiSewer_result <- load_EpiSewer_results("_overview_23-24")
data_PCR_agg_select <- get_data_PCR_agg_select("_overview_23-24")
data_flow_select <- get_data_flow_select("_overview_23-24")
```

Build index
```{r}
results_index_mobility <- bind_rows(lapply(job_EpiSewer_result_mobility, function(x) {
  if (length(x) == 0) { data.frame(wwtp = NA, target = NA, estimation_date = NA)
  } else {
    return(data.frame(
      wwtp = x$job$selection$wwtp,
      target = x$job$selection$target,
      estimation_date = lubridate::as_date(x$job$selection$date_select[[1]]["to"]),
      season = ifelse(lubridate::as_date(x$job$selection$date_select[[1]]["to"])<"2023-08-01","2022/23","2023/24"),
      mobility = TRUE
  ))}
  }))
rownames(results_index_mobility) <- NULL
results_index_mobility$i <- 1:nrow(results_index_mobility)

results_index <- bind_rows(lapply(job_EpiSewer_result, function(x) {
  if (length(x) == 0) { data.frame(wwtp = NA, target = NA, estimation_date = NA)
  } else {
    return(data.frame(
      wwtp = x$job$selection$wwtp,
      target = x$job$selection$target,
      estimation_date = lubridate::as_date(x$job$selection$date_select[[1]]["to"]),
      season = ifelse(lubridate::as_date(x$job$selection$date_select[[1]]["to"])<"2023-08-01","2022/23","2023/24"),
      mobility = FALSE
  ))}
  }))
rownames(results_index) <- NULL
results_index$i <- 1:nrow(results_index)
```

## Plotting
```{r}
selection_list <- list(
  list(wwtp_select = "ARA Werdhoelzli", target_select = "SARS-N2", R_lim = c(0.8, 1.2))
)
```

```{r}
palette_mobility <- c("Commuting (25% reduction on weekends/holidays)"="#BC3C29FF", "Constant"="black")
```

```{r}
lapply(selection_list, function(selection) {
date_lim <- as.Date(c("2023-08-30", "2024-04-15"))

results_select <- list(
    `Commuting (25% reduction on weekends/holidays)` = job_EpiSewer_result_mobility[[results_index_mobility |> filter(wwtp == selection$wwtp_select, target == selection$target_select) |> pull(i) |> as.integer()]],
  Constant = job_EpiSewer_result[[results_index |> filter(wwtp == selection$wwtp_select, target == selection$target_select) |> pull(i) |> as.integer()]]
)

data_PCR_select <- left_join(
  data_PCR_agg_select_mobility[[results_index_mobility |> filter(wwtp == selection$wwtp_select, target == selection$target_select) |> pull(i) |> as.integer()]] |> filter(wwtp == selection$wwtp_select, target == selection$target_select),
  data_PCR_agg_select[[results_index |> filter(wwtp == selection$wwtp_select, target == selection$target_select) |> pull(i) |> as.integer()]] |> filter(wwtp == selection$wwtp_select, target == selection$target_select), by = c("target", "wwtp", "date", "n_reps", "dilution", "total_droplets"), suffix = c("_mobility", "_baseline")
) |> left_join(
  data_flow_select_mobility[[results_index_mobility |> filter(wwtp == selection$wwtp_select) |> pull(i) |> as.integer()]] |> 
    filter(wwtp == selection$wwtp_select), by = c("wwtp", "date")
) |> mutate(gc_per_mlww_norm_mobility = gc_per_mlww_mobility * flow / median(flow), gc_per_mlww_norm_baseline = gc_per_mlww_baseline * flow / median(flow))

ymax <- results_select[[1]]$summary$concentration[, max(upper_0.95)]
                                        
concentration_plot <- plot_concentration(
  results_select,
  concentration_col = "gc_per_mlww", normalized = TRUE,
  forecast = FALSE, median = T) + theme(legend.position = "top", legend.title = element_text()) + 
  coord_cartesian(ylim = c(0, ymax)) +
  scale_color_manual(name = "Population size", values = palette_mobility) +
  scale_fill_manual(name = "Population size", values = palette_mobility) +
  coord_cartesian(xlim = date_lim, ylim = c(0, 2300)) +
  scale_y_continuous(expand = expansion(add = c(5, 10))) +
  ylab(expression(Normalized~C[t]~plain("[gc / mL]"))) +
  geom_segment(data = data_PCR_select |> filter(abs(gc_per_mlww_norm_mobility-gc_per_mlww_norm_baseline)>0.1), aes(x = date, xend = date, y = gc_per_mlww_norm_baseline, yend = gc_per_mlww_norm_mobility), color = palette_mobility["Commuting (25% reduction on weekends/holidays)"], linewidth = 0.5, linetype = "dotted") +
  geom_point(data = data_PCR_select, aes(x = date, y = gc_per_mlww_norm_baseline), shape = 16, size = 1, color = palette_mobility["Constant"]) + geom_point(data = data_PCR_select |> filter(abs(gc_per_mlww_norm_mobility-gc_per_mlww_norm_baseline)>0.1), aes(x = date, y = gc_per_mlww_norm_mobility), shape = 17, size = 1, color = palette_mobility["Commuting (25% reduction on weekends/holidays)"])
  

load_plot <- plot_load(results_select, median = T, forecast = FALSE) + 
  theme(legend.position = "top", legend.title = element_text()) +
  scale_color_manual(name = "Population size", values = palette_mobility) +
  scale_fill_manual(name = "Population size", values = palette_mobility) +
  coord_cartesian(xlim = date_lim)

infection_plot <- plot_infections(results_select, median = T, forecast = FALSE) + 
  theme(legend.position = "top", legend.title = element_text()) +
  scale_color_manual(name = "Population size", values = palette_mobility) +
  scale_fill_manual(name = "Population size", values = palette_mobility) +
  coord_cartesian(xlim = date_lim)

R_plot <- plot_R(results_select, median = T, forecast = FALSE) + 
  theme(legend.position = "top", legend.title = element_text()) +
  scale_color_manual(name = "Population size", values = palette_mobility) +
  scale_fill_manual(name = "Population size", values = palette_mobility) +
  coord_cartesian(xlim = date_lim, ylim = selection$R_lim)

combined_plot <- cowplot::plot_grid(
  concentration_plot + theme(axis.title.x = element_blank(), axis.text.x = element_blank()),
  R_plot + theme(legend.position = "none", axis.title.x = element_blank()) +
    ylab(expression(R[t])),
  ncol = 1, align = "v", rel_heights = c(0.53, 0.47)
)

print(combined_plot)
ggsave(plot = combined_plot, file = here::here("figures", "mobility", paste0("mobility_", selection$wwtp_select, "_", selection$target_select, ".pdf")), width = 10, height = 5)
})
```


