```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r}
library(targets)
library(dplyr)
library(EpiSewer)
library(ggplot2)
source("code/pipeline/utils_pipeline.R")
source("code/pipeline/utils_real_time.R")
source("data/assumptions/epi_params_EpiSewer-study.R")
source("code/local_config.R")
```

Create pipeline folders if they do not exist
```{r}
setup_pipeline("_subsampling")
```

## Run pipelines
```{r, include = FALSE}
  run_pipeline(targets_proj_name = "_subsampling", submit = TRUE)
if(length(tar_read(jobs_EpiSewer_invalid))>0) {
  warning("There are invalid jobs.")
}
```

Check results
```{r}
tar_load(job_EpiSewer_submission)

job_EpiSewer_submission |>
  mutate(total = 1, .before = exists) |>
  summarise(across(total:submitted, \(x) sum(x, na.rm = T)))
```

## Load results
```{r}
setup_pipeline("_subsampling")
tar_load(job_EpiSewer_result)
tar_load(data_PCR_agg_select)
tar_load(subsampling)
```

### Overall performance

```{r}
palette_targets <- c("SARS-CoV-2" = "#BC3C29FF", "IAV" = "#0072B5FF", "RSV" = "#E18727FF")
target_labels <- list(
  `SARS-N2` = "SARS-CoV-2",
  `IAV-M` = "IAV",
  `RSV-N` = "RSV"
)
palette_approaches <- c("EpiSewer" = "#1f407a")
```

```{r}
R_results_all_EpiSewer <- rbindlist(lapply(job_EpiSewer_result, function(x) {
  if (length(x) == 0) return(NULL)
  R_result <- x$summary$R
  R_result[, wwtp := x$job$selection$wwtp]
  R_result[, target := x$job$selection$target]
  R_result[, subsampling_type := x$job$selection$subsampling[[1]]$type]
  R_result[, subsampling_subtype := x$job$selection$subsampling[[1]]$subtype]
  return(R_result)
}))
R_results_all_EpiSewer[, approach := "EpiSewer"]
```

```{r}
R_results_all <- R_results_all_EpiSewer

# add gold standard (full days)
R_results_all <- merge(R_results_all, R_results_all[subsampling_type == "5 days per week",c("wwtp", "target", "approach", "date", "median", "lower_0.95", "upper_0.95")], by = c("wwtp","target","approach","date"), suffixes = c("", "_full"), all.x = TRUE)

# add naive baseline (Rt=1)
scaled_baseline <- R_results_all[subsampling_type == "5 days per week" & approach == "EpiSewer",]
scaled_baseline[, baseline_error := median - 1]
R_results_all <- merge(R_results_all, scaled_baseline[, c("wwtp", "target", "date", "baseline_error")],
, by = c("wwtp","target","date"), all.x = TRUE)
```

```{r}
targets_select <- c("SARS-N2", "IAV-M", "RSV-N")
wave_dates <- readr::read_csv(here::here("data", "assumptions", "wave_dates.csv")) |> filter(season == "2023/24")
R_results_all <- merge(R_results_all, wave_dates, by = c("wwtp","target"))
R_results_all[, target := factor(target, levels = names(target_labels), labels = target_labels, ordered = TRUE)]
```

Quantitative results
```{r}
MAE_summary <- R_results_all[subsampling_type!="5 days per week" & approach == "EpiSewer" & date >= start_date & date <= end_date, list(MAE = mean(abs(median-median_full))), by = c("wwtp", "target", "approach", "subsampling_type", "subsampling_subtype")]
  
MAE_summary <- MAE_summary[, list(MAE_min = min(MAE), MAE_max = max(MAE)), by = c("wwtp", "target", "approach", "subsampling_type")]
```

MAE plot
```{r fig.width=10, fig.height=5}
error_plot_data <- R_results_all[approach == "EpiSewer" & date >= start_date & date <= end_date, list(MAE = mean(abs(median-median_full))), by = c("wwtp", "target", "approach", "subsampling_type", "subsampling_subtype")]
error_plot_data[, subsampling_type := stringr::str_replace(subsampling_type, "per", "\nper")]

error_plot <- error_plot_data |> 
  ggplot(aes(x=forcats::fct_rev(subsampling_type), y = MAE, color = target)) +
  geom_boxplot(outliers = FALSE) +
  geom_point(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.2), size = 0.7) +
  ylab(expression(MAE~of~median~R[t])) +
  theme_bw() +
  facet_wrap(~ target, nrow = 1) +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    axis.title.x = element_blank(),
    strip.background = element_rect(fill = "white")
    ) +
  scale_color_manual(values = palette_targets) +
  coord_cartesian(ylim = c(0, 0.15))
error_plot
```

Width of uncertainty intervals
```{r fig.width=10, fig.height=5}
width_plot_data <- R_results_all[approach == "EpiSewer"  & date>=start_date & date<=end_date, .(spread = mean(upper_0.95 - lower_0.95)), by = c("wwtp", "target", "approach", "subsampling_type", "subsampling_subtype")]
width_plot_data[, subsampling_type := stringr::str_replace(subsampling_type, "per", "\nper")]

width_plot <- width_plot_data |> 
  ggplot(aes(x=forcats::fct_rev(subsampling_type), y = spread, color = target)) +
  geom_boxplot(outliers = FALSE) +
  geom_point(position = position_jitterdodge(jitter.height = 0)) +
  facet_wrap(~ target, nrow = 1) +
  ylab("Mean 95% CrI width") +
  theme_bw() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    strip.background = element_rect(fill = "white")
    ) +
  scale_color_manual(values = palette_targets) +
  coord_cartesian(ylim = c(0, 0.8))
width_plot
```
```{r fig.width=10, fig.height=5}
plotlegend <- cowplot::get_plot_component(error_plot, pattern = "guide-box-top")
cowplot::plot_grid(
  plotlegend, error_plot + theme(legend.position = "none"), width_plot, ncol = 1, rel_heights = c(0.1, 0.5, 0.5), labels = c("", "A", "B")
)
ggsave(here::here("figures", "subsampling", "subsampling_MAE_and_width.pdf"), width = 10, height = 5, scale = 0.9)
```

## Example Rt estimates over time
```{r}
target_R_lim <- list(
  `SARS-N2` = c(0.7, 1.3),
  `IAV-M` = c(0.7, 1.5),
  `RSV-N` = c(0.6, 1.9)
)
```

```{r}
appraoch_select <- "EpiSewer"
subsampling_subtypes_selection <- c("(Monday|Tuesday)+(Wednesday|Thursday)+Friday", "Friday", "Friday")
date_lim <- as.Date(c("2023-08-15", "2024-05-31"))

baseline <- R_results_all[approach == appraoch_select & subsampling_type == "5 days per week" & date>=date_lim[1] & date <= date_lim[2],]
baseline <- baseline[, subsampling_type := NULL]

example_subsampling_figure <- R_results_all |> distinct(approach, wwtp, target, date, subsampling_type, subsampling_subtype, .keep_all = TRUE) |> filter(approach == appraoch_select & subsampling_subtype %in% subsampling_subtypes_selection & date>=date_lim[1] & date <= date_lim[2]) |> 
  mutate(subsampling_type = factor(subsampling_type, levels = c("3 days per week", "1 day per week", "1 day per 2 weeks"))) |>
  ggplot(aes(x=date, y=median, color = target)) + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_ribbon(data = baseline, aes(ymin = lower_0.95, ymax = upper_0.95), fill = "black", alpha = 0.2, color = NA) +
  geom_ribbon(data = baseline, aes(ymin = lower_0.5, ymax = upper_0.5), fill = "black", alpha = 0.3, color = NA) +
  geom_line(data = baseline, color = "black", alpha = 0.9) +
  geom_ribbon(aes(ymin = lower_0.95, ymax = upper_0.95, fill = target), alpha = 0.2, color = NA) +
  geom_ribbon(aes(ymin = lower_0.5, ymax = upper_0.5, fill = target), alpha = 0.3, color = NA) +
  geom_line() +
  facet_grid(target ~ subsampling_type, scales = "free_y") +
  theme_bw() + 
  coord_cartesian(xlim = date_lim)  +
  scale_color_manual(values = palette_targets) +
  scale_fill_manual(values = palette_targets) +
  scale_x_date(date_breaks = "3 months", date_labels = "%b '%y", expand = c(0,0)) +
  ylab(expression(R[t])) +
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "white"),
    axis.title.x = element_blank()
    )
example_subsampling_figure
```

```{r}
library(ggh4x)
appraoch_select <- "EpiSewer"
date_lim <- as.Date(c("2023-08-15", "2024-05-31"))

baseline <- R_results_all[approach == appraoch_select & subsampling_type == "5 days per week" & date>=date_lim[1] & date <= date_lim[2],]
baseline <- baseline[, subsampling_type := NULL]

example_subsampling_figure_all <- R_results_all |> distinct(approach, wwtp, target, date, subsampling_type, subsampling_subtype, .keep_all = TRUE) |> filter(approach == appraoch_select & subsampling_type != "5 days per week" & date>=date_lim[1] & date <= date_lim[2]) |> 
  mutate(subsampling_type = factor(subsampling_type, levels = c("3 days per week", "1 day per week", "1 day per 2 weeks"))) |>
  ggplot(aes(x=date, y=median, color = target)) + 
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_ribbon(aes(ymin = lower_0.95, ymax = upper_0.95, fill = target, group = subsampling_subtype), alpha = 0.1, color = NA) +
  geom_ribbon(aes(ymin = lower_0.5, ymax = upper_0.5, fill = target, group = subsampling_subtype), alpha = 0.2, color = NA) +
  geom_ribbon(data = baseline, aes(ymin = lower_0.95, ymax = upper_0.95), fill = "black", alpha = 0.2, color = NA) +
  geom_ribbon(data = baseline, aes(ymin = lower_0.5, ymax = upper_0.5), fill = "black", alpha = 0.3, color = NA) +
  geom_line(data = baseline, color = "black", alpha = 0.9) +
  geom_line(aes(group = subsampling_subtype), linewidth = 0.3, alpha = 0.9) +
  facet_grid(target ~ subsampling_type, scales = "free_y") +
  facetted_pos_scales(y = list(
    scale_y_continuous(limits = c(0.7, 1.3)),
    scale_y_continuous(limits = c(0.6, 1.4)),
    scale_y_continuous(limits = c(0.5, 1.8)
  ))) +
  theme_bw() + 
  scale_y_continuous(breaks = seq(0.6, 1.6, 0.4)) +
  coord_cartesian(xlim = date_lim)  +
  scale_color_manual(values = palette_targets) +
  scale_fill_manual(values = palette_targets) +
  scale_x_date(date_breaks = "3 months", date_labels = "%b '%y", expand = c(0,0)) +
  ylab(expression(R[t])) +
  theme(
    legend.position = "none",
    strip.background = element_rect(fill = "white"),
    axis.title.x = element_blank()
    )
example_subsampling_figure_all
ggsave(here::here("figures", "subsampling", "subsampling_example_all.pdf"), width = 10, height = 5, scale = 0.9)
```
